version: "3.8"

services:
  backend:
    build: ./backend
    container_name: note_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://nhducjob_db_user:IybmBrCS6WjBocYx@ac-w9ipkd3-shard-00-00.skdwjrt.mongodb.net:27017,ac-w9ipkd3-shard-00-01.skdwjrt.mongodb.net:27017,ac-w9ipkd3-shard-00-02.skdwjrt.mongodb.net:27017/?ssl=true&replicaSet=atlas-8yztb9-shard-0&authSource=admin&appName=Cluster0
      JWT_SECRET: your_jwt_secret_here
      CLOUDINARY_CLOUD_NAME: dcty19cgo
      CLOUDINARY_API_KEY: 235197989411593
      CLOUDINARY_API_SECRET: TrtnRpj8JFRClBnvgBKxT1j0joI
      EMAIL_USER: pokemongo99113@gmail.com
      EMAIL_PASS: lznp arwx kjva cgiw

  frontend:
    build: ./frontend
    container_name: note_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

# Xóa luôn phần volumes vì không dùng MongoDB container nữa