const express = require('express');
const router  = express.Router();
const Note    = require('../models/Note');
const User    = require('../models/User');
const transporter = require('../config/mailer');

// ── Helper: Send note sharing notification email ──────────
async function sendShareNotification({ toEmail, toName, ownerName, noteTitle, permission }) {
  const permLabel = permission === 'edit' ? 'edit' : 'view';
  const mailOptions = {
    from: `"NoteSpace" <${process.env.EMAIL_USER}>`,
    to: toEmail,
    subject: `${ownerName} has shared a note with you`,
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:auto;padding:32px;border:1px solid #e5e7eb;border-radius:12px">
        <h2 style="color:#5147d4;margin-bottom:8px">📒 NoteSpace</h2>
        <p style="font-size:16px;color:#0f172a">Hello <strong>${toName || toEmail}</strong>,</p>
        <p style="color:#334155">
          <strong>${ownerName}</strong> just shared the note
          <strong>"${noteTitle || 'Untitled'}"</strong> with you.
        </p>
        <div style="background:#f1f5f9;border-left:4px solid #5147d4;padding:12px 16px;border-radius:6px;margin:20px 0">
          <span style="color:#5147d4;font-weight:600">Your permission: ${permLabel}</span>
        </div>
        <p style="color:#64748b;font-size:13px">Log in to NoteSpace to view the shared note.</p>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0"/>
        <p style="color:#94a3b8;font-size:12px">This email is automatically generated by NoteSpace. Please do not reply.</p>
      </div>
    `,
  };
  try {
    await transporter.sendMail(mailOptions);
  } catch (err) {
    console.error('[Mail] Failed to send share notification:', err.message);
  }
}

// PATCH /:id/share — Share a note with another user
router.patch('/:id/share', async (req, res) => {
  try {
    const { email, permission, requesterId } = req.body;
    if (!email || !permission || !requesterId)
      return res.status(400).json({ error: 'Missing required fields' });

    const note = await Note.findById(req.params.id);
    if (!note) return res.status(404).json({ error: 'Note not found' });
    if (note.userId.toString() !== requesterId)
      return res.status(403).json({ error: 'Only the owner can share this note' });

    const targetUser = await User.findOne({ email: email.toLowerCase().trim() });
    if (!targetUser) return res.status(404).json({ error: 'No account found with this email' });
    if (targetUser._id.toString() === requesterId)
      return res.status(400).json({ error: 'You cannot share a note with yourself' });

    const owner = await User.findById(requesterId).select('username email');

    const isNew = !note.sharedWith.find(s => s.userId.toString() === targetUser._id.toString());
    const existing = note.sharedWith.find(s => s.userId.toString() === targetUser._id.toString());
    if (existing) {
      existing.permission = permission;
    } else {
      note.sharedWith.push({ userId: targetUser._id, email: targetUser.email, permission });
    }
    await note.save();

    // Socket broadcast
    const io = req.app.get('io');
    const sharePayload = { noteId: note._id.toString() };
    io.to(`user:${targetUser._id.toString()}`).emit('note-shared', sharePayload);
    io.to(`user:${requesterId}`).emit('note-shared', sharePayload);

    // Send notification email (only for new shares, not when changing permissions)
    if (isNew) {
      sendShareNotification({
        toEmail:    targetUser.email,
        toName:     targetUser.username,
        ownerName:  owner?.username || 'Someone',
        noteTitle:  note.title,
        permission,
      });
    }

    res.json({ success: true, sharedWith: note.sharedWith });
  } catch (err) {
    res.status(500).json({ error: 'Failed to share note' });
  }
});

// PATCH /:id/share/permission — Change permissions
router.patch('/:id/share/permission', async (req, res) => {
  try {
    const { targetUserId, permission, requesterId } = req.body;
    const note = await Note.findById(req.params.id);
    if (!note) return res.status(404).json({ error: 'Note not found' });
    if (note.userId.toString() !== requesterId)
      return res.status(403).json({ error: 'Only the owner can change permissions' });
    const entry = note.sharedWith.find(s => s.userId.toString() === targetUserId);
    if (!entry) return res.status(404).json({ error: 'Share entry not found' });
    entry.permission = permission;
    await note.save();
    res.json({ success: true, sharedWith: note.sharedWith });
  } catch (err) {
    res.status(500).json({ error: 'Failed to update permission' });
  }
});

// DELETE /:id/share/:targetUserId — Revoke access for a single user
router.delete('/:id/share/:targetUserId', async (req, res) => {
  try {
    const { requesterId } = req.body;
    const note = await Note.findById(req.params.id);
    if (!note) return res.status(404).json({ error: 'Note not found' });
    if (note.userId.toString() !== requesterId)
      return res.status(403).json({ error: 'Only the owner can revoke access' });

    const removedUserId = req.params.targetUserId;
    note.sharedWith = note.sharedWith.filter(s => s.userId.toString() !== removedUserId);
    await note.save();

    const io = req.app.get('io');
    io.to(`user:${removedUserId}`).emit('note-unshared', { noteId: note._id.toString() });
    io.to(`user:${requesterId}`).emit('note-unshared', { noteId: note._id.toString() });

    res.json({ success: true, sharedWith: note.sharedWith });
  } catch (err) {
    res.status(500).json({ error: 'Failed to revoke access' });
  }
});

// DELETE /:id/share — Revoke all access
router.delete('/:id/share', async (req, res) => {
  try {
    const { requesterId } = req.body;
    const note = await Note.findById(req.params.id);
    if (!note) return res.status(404).json({ error: 'Note not found' });
    if (note.userId.toString() !== requesterId)
      return res.status(403).json({ error: 'Only the owner can revoke all access' });

    const removedUsers = [...note.sharedWith];
    note.sharedWith = [];
    await note.save();

    const io = req.app.get('io');
    for (const s of removedUsers) {
      io.to(`user:${s.userId.toString()}`).emit('note-unshared', { noteId: note._id.toString() });
    }

    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: 'Failed to revoke all shares' });
  }
});

module.exports = router;